name: Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        node-version: [18.x]
        dependency-version: [prefer-lowest, prefer-stable]
    name: Test Node-${{ matrix.node-version }} on ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm i -g pnpm && pnpm install
    - name: Run tests
      run: pnpm test
